/*
 * Copyright (c) Quinn Hooft (Stetsed)
 * SPDX-License-Identifier: MIT
 */

#ifndef STD_STUPID_BINDGEN
#define STD_STUPID_BINDGEN

#pragma once

/* Generated with cbindgen:0.28.0 */

/* Do not modify. This code was autogenerated by bindgen. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

typedef enum MessageType {
  Set,
  Get,
  Check,
  Reset,
} MessageType;

typedef struct Vec_CString Vec_CString;

typedef struct Packet {
  enum MessageType Mode;
  uint8_t Other;
  struct Vec_CString Key;
  struct Vec_CString Value;
} Packet;

const CString *get_key(const struct Packet *self, size_t index);

const CString *get_value(const struct Packet *self, size_t index);

/**
 * Takes in an array of bytes, the length of this array, and a struct of type Packet.
 *
 * * `input_bytes_ptr` - Array of bytes that has been received for communication
 * * `len` - Length of array pointed to by input_bytes_ptr
 * * `return_struct` - Struct of type Packet that is initialized
 *
 * # Safety
 *
 * Function has a guarantee to be safe against NULL Pointer and a non-aligned pointer due to it
 * being const and having a type size of 1, however it can still cause undefined behavior because it
 * assumes that the "input_bytes_ptr" is a pointer an array of bytes of length "len"
 */
int8_t parse_packet(const uint8_t *input_bytes_ptr, size_t len, struct Packet *return_struct);

#endif  /* STD_STUPID_BINDGEN */
