extern crate cbindgen;

use std::env;

use cbindgen::*;

fn main() {
    let crate_dir = env::var("CARGO_MANIFEST_DIR").unwrap();

    let warning = "/* Do not modify. This code was autogenerated by bindgen. */";

    let struct_config = StructConfig {
        rename_fields: cbindgen::RenameRule::PascalCase,
        derive_constructor: true,
        derive_eq: true,
        derive_neq: true,
        derive_lt: true,
        derive_gt: true,
        derive_gte: true,
        derive_lte: true,
        ..Default::default()
    };

    let config = Config {
        usize_is_size_t: true,
        documentation_style: cbindgen::DocumentationStyle::Doxy,
        structure: struct_config,
        ..Default::default()
    };

    Builder::new()
        .with_config(config)
        .with_language(cbindgen::Language::C)
        .with_crate(crate_dir)
        .with_autogen_warning(warning)
        .with_include_guard("STD_STUPID_BINDGEN")
        .with_pragma_once(true)
        .with_include_version(true)
        .generate()
        .expect("cbindgen failed to generate bindings")
        .write_to_file("bindings.h");
}
